/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    HealthcareHome: typeof import('./src/components/HealthcareHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
  const BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
  const BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
  const BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
  const HealthcareHome: typeof import('./src/components/HealthcareHome.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}